/**
 * 物品目录 — 市场 / 仓库 / 装备栏共用
 */
(function () {
  "use strict";

  var ITEMS = {
    medkit: {
      id: "medkit",
      name: "野战医疗包",
      type: "loot",
      w: 1,
      h: 2,
      image: null,
    },
    bolt: {
      id: "bolt",
      name: "螺栓组",
      type: "loot",
      w: 1,
      h: 2,
    },
    truck_part: {
      id: "truck_part",
      name: "卡车部件",
      type: "loot",
      w: 2,
      h: 2,
    },
    circuit: {
      id: "circuit",
      name: "废弃电路板",
      type: "loot",
      w: 1,
      h: 1,
    },
    sealed_motor_oil: {
      id: "sealed_motor_oil",
      name: "密封的特种机油",
      type: "loot",
      w: 1,
      h: 2,
      rarity: "common",
      rarityLabel: "普通",
      rarityIcon: "🟢",
      category: "industrial",
      reclaimMin: 1200,
      minMarketPrice: 1000,
      maxMarketPrice: 3200,
      flavor:
        "重型工业垃圾。背包实在没东西装时，才会勉强带走的垫底物资。",
      image: "img/market/sealed-motor-oil.png?v=3",
    },
    heavy_industrial_drill: {
      id: "heavy_industrial_drill",
      name: "重型工业钻头",
      type: "loot",
      w: 3,
      h: 2,
      rarity: "epic",
      rarityLabel: "史诗",
      rarityIcon: "🟣",
      category: "industrial",
      reclaimMin: 38000,
      minMarketPrice: 35000,
      maxMarketPrice: 80000,
      flavor:
        "高价值工业品。极其占格子——带一枚大钻头，还是带六块小电路板？",
      image: "img/market/heavy-industrial-drill.svg",
    },
    helm_basic: {
      id: "helm_basic",
      name: "战术头盔",
      type: "helmet",
      w: 1,
      h: 1,
      image: "img/market/helmet.svg",
    },
    armr_basic: {
      id: "armr_basic",
      name: "轻型护甲",
      type: "armor",
      w: 1,
      h: 1,
      image: "img/market/armor.svg",
    },
    rig_light: {
      id: "rig_light",
      name: "轻型弹挂",
      type: "rig",
      w: 1,
      h: 1,
      rigSlots: 6,
      image: "img/market/rig-light.svg",
    },
    bp_sport: {
      id: "bp_sport",
      name: "运动背包",
      type: "backpack",
      w: 1,
      h: 1,
      cols: 2,
      rows: 4,
      image: "img/market/backpack-sport.svg",
    },
    bp_light: {
      id: "bp_light",
      name: "轻型背包",
      type: "backpack",
      w: 1,
      h: 1,
      cols: 3,
      rows: 4,
      image: "img/market/backpack-light.svg",
    },
    brass_bullet: {
      id: "brass_bullet",
      name: "黄铜子弹",
      type: "ammo",
      w: 1,
      h: 1,
      stackSize: 60,
      rarity: "common",
      rarityLabel: "普通",
      rarityIcon: "🟢",
      category: "ammo",
      reclaimMin: 12000,
      flavor: "黄铜制式步枪弹，60 发装一组，占 1 格。",
      image: "img/market/brass-bullet.svg",
      model3d: "models/brass-bullet.glb",
    },
    uzi_smg: {
      id: "uzi_smg",
      name: "UZI 冲锋枪",
      type: "weapon_primary",
      w: 3,
      h: 2,
      rarity: "rare",
      rarityLabel: "稀有",
      rarityIcon: "🔵",
      category: "weapon",
      reclaimMin: 2900,
      flavor: "改良冲锋枪，占 6 格，可装备主武器栏。",
      image: "img/market/uzi-smg.svg",
      model3d: "models/uzi.glb",
    },
    pirate_1001: {
      id: "pirate_1001",
      name: "废弃的军用电路板",
      type: "loot",
      w: 1,
      h: 1,
      rarity: "common",
      rarityLabel: "普通",
      rarityIcon: "🟢",
      reclaimMin: 500,
      minMarketPrice: 1000,
      maxMarketPrice: 1000,
      category: "collectible",
    },
    pirate_1002: {
      id: "pirate_1002",
      name: "完整的无人机镜头",
      type: "loot",
      w: 2,
      h: 2,
      rarity: "epic",
      rarityLabel: "史诗",
      rarityIcon: "🟣",
      reclaimMin: 60000,
      minMarketPrice: 100000,
      maxMarketPrice: 100000,
      category: "collectible",
    },
    pirate_1003: {
      id: "pirate_1003",
      name: "绝密航线硬盘",
      type: "loot",
      w: 1,
      h: 2,
      rarity: "epic",
      rarityLabel: "史诗",
      rarityIcon: "🟣",
      reclaimMin: 34000,
      minMarketPrice: 87000,
      maxMarketPrice: 87000,
      category: "collectible",
    },
    collectible_3001: {
      id: "collectible_3001",
      name: "前线指挥官的合金火机",
      type: "loot",
      w: 1,
      h: 1,
      rarity: "legendary",
      rarityLabel: "传奇",
      rarityIcon: "🟡",
      reclaimMin: 210000,
      minMarketPrice: 350000,
      maxMarketPrice: 350000,
      category: "collectible",
    },
    collectible_3002: {
      id: "collectible_3002",
      name: "复古废土手摇八音盒",
      type: "loot",
      w: 1,
      h: 1,
      rarity: "legendary",
      rarityLabel: "传奇",
      rarityIcon: "🟡",
      reclaimMin: 160000,
      minMarketPrice: 260000,
      maxMarketPrice: 260000,
      category: "collectible",
    },
    collectible_3003: {
      id: "collectible_3003",
      name: "全息推演沙盘",
      type: "loot",
      w: 2,
      h: 2,
      rarity: "epic",
      rarityLabel: "史诗",
      rarityIcon: "🟣",
      reclaimMin: 60000,
      minMarketPrice: 95000,
      maxMarketPrice: 95000,
      category: "collectible",
    },
    collectible_3004: {
      id: "collectible_3004",
      name: "已停产的初代微光观测镜",
      type: "loot",
      w: 1,
      h: 2,
      rarity: "epic",
      rarityLabel: "史诗",
      rarityIcon: "🟣",
      reclaimMin: 48000,
      minMarketPrice: 75000,
      maxMarketPrice: 75000,
      category: "collectible",
    },
    collectible_3005: {
      id: "collectible_3005",
      name: "极危行动初代荣誉勋章",
      type: "loot",
      w: 1,
      h: 1,
      rarity: "rare",
      rarityLabel: "稀有",
      rarityIcon: "🔵",
      reclaimMin: 24000,
      minMarketPrice: 38000,
      maxMarketPrice: 38000,
      category: "collectible",
    },
    pirate_1004: {
      id: "pirate_1004",
      name: "纯金战术指挥鹰雕像",
      type: "loot",
      w: 2,
      h: 2,
      rarity: "legendary",
      rarityLabel: "传奇",
      rarityIcon: "🟡",
      reclaimMin: 300000,
      minMarketPrice: 500000,
      maxMarketPrice: 500000,
      category: "collectible",
    },
    pirate_1005: {
      id: "pirate_1005",
      name: "未知生物血清样本",
      type: "loot",
      w: 1,
      h: 1,
      rarity: "legendary",
      rarityLabel: "传奇",
      rarityIcon: "🟡",
      reclaimMin: 250000,
      minMarketPrice: 450000,
      maxMarketPrice: 450000,
      category: "collectible",
    },
    pirate_1006: {
      id: "pirate_1006",
      name: "军用加密对讲机",
      type: "loot",
      w: 1,
      h: 1,
      rarity: "rare",
      rarityLabel: "稀有",
      rarityIcon: "🔵",
      reclaimMin: 3000,
      minMarketPrice: 10000,
      maxMarketPrice: 10000,
      category: "collectible",
    },
    pirate_1007: {
      id: "pirate_1007",
      name: "高清特工夜视仪(损坏)",
      type: "loot",
      w: 1,
      h: 2,
      reclaimMin: 9000,
      category: "collectible",
    },
  };

  var STASH_TO_ITEM = {
    circuit: "circuit",
    spoil: "sealed_motor_oil",
    hidrl: "heavy_industrial_drill",
    helm1: "helm_basic",
    armr1: "armr_basic",
    riglt: "rig_light",
    bpspt: "bp_sport",
    bplgt: "bp_light",
    brslv: "brass_bullet",
    uzism: "uzi_smg",
    p1001: "pirate_1001",
    p1002: "pirate_1002",
    p1003: "pirate_1003",
    p1004: "pirate_1004",
    p1005: "pirate_1005",
    p1006: "pirate_1006",
    c3001: "collectible_3001",
    c3002: "collectible_3002",
    c3003: "collectible_3003",
    c3004: "collectible_3004",
    c3005: "collectible_3005",
  };

  var SLOT_TYPES = {
    primary: ["weapon_primary"],
    melee: ["weapon_melee"],
    secondary: ["weapon_secondary"],
    pistol: ["weapon_pistol"],
    helmet: ["helmet"],
    armor: ["armor"],
    rig: ["rig"],
    backpack: ["backpack"],
    card: ["keycard", "loot"],
  };

  function getItem(id) {
    return ITEMS[id] ? Object.assign({}, ITEMS[id]) : null;
  }

  function fromStashId(stashId) {
    var itemId = STASH_TO_ITEM[stashId];
    return itemId ? getItem(itemId) : null;
  }

  function acceptsSlot(slotKey, item) {
    if (!item) return false;
    var allowed = SLOT_TYPES[slotKey];
    if (!allowed) return false;
    if (allowed.indexOf(item.type) >= 0) return true;
    if (slotKey === "card" && item.type === "loot") return true;
    return false;
  }

  window.ItemCatalog = {
    ITEMS: ITEMS,
    STASH_TO_ITEM: STASH_TO_ITEM,
    getItem: getItem,
    fromStashId: fromStashId,
    acceptsSlot: acceptsSlot,
  };
})();
