/**
 * 物品目录 — 市场 / 仓库 / 装备栏共用
 */
(function () {
  "use strict";

  var ITEMS = {
    keycard: {
      id: "keycard",
      name: "钥匙卡",
      type: "keycard",
      w: 1,
      h: 1,
      maxDurability: 10,
      image: "img/market/keycard-side-entrance.png",
    },
    keycard_president_office: {
      id: "keycard_president_office",
      name: "总统办公室",
      type: "keycard",
      w: 1,
      h: 1,
      maxDurability: 10,
      access: "president_office",
      minMarketPrice: 4000000,
      maxMarketPrice: 4000000,
      reclaimMin: 3600000,
      image: "img/market/keycard-side-entrance.png",
    },
    medkit: {
      id: "medkit",
      name: "野战医疗包",
      type: "loot",
      w: 1,
      h: 2,
      image: null,
      model3d: "models/antique-lockbox.glb",
    },
    almond_water: {
      id: "almond_water",
      name: "杏仁水",
      type: "consumable",
      w: 1,
      h: 1,
      stackSize: 4,
      rarity: "common",
      rarityLabel: "普通",
      rarityIcon: "🟢",
      category: "backrooms",
      reclaimMin: 80,
      flavor:
        "后室最常见的补给。淡杏仁味，能缓解口渴与理智流失。",
      image: "img/backrooms/almond-water.png",
      model3d: "models/futuristic-device.glb",
    },
    bolt: {
      id: "bolt",
      name: "螺栓组",
      type: "loot",
      w: 1,
      h: 2,
      model3d: "models/brass-bullet.glb",
    },
    truck_part: {
      id: "truck_part",
      name: "卡车部件",
      type: "loot",
      w: 2,
      h: 2,
      model3d: "models/futuristic-device.glb",
    },
    circuit: {
      id: "circuit",
      name: "废弃电路板",
      type: "loot",
      w: 1,
      h: 1,
      model3d: "models/futuristic-device.glb",
    },
    sealed_motor_oil: {
      id: "sealed_motor_oil",
      name: "特种机油",
      type: "loot",
      w: 1,
      h: 2,
      rarity: "common",
      rarityLabel: "普通",
      rarityIcon: "🟢",
      category: "industrial",
      reclaimMin: 1200,
      minMarketPrice: 1000,
      maxMarketPrice: 3200,
      flavor:
        "重型工业垃圾。背包实在没东西装时，才会勉强带走的垫底物资。",
      image: "img/market/sealed-motor-oil.png?v=3",
      model3d: "models/futuristic-device.glb",
    },
    heavy_industrial_drill: {
      id: "heavy_industrial_drill",
      name: "重型工业钻头",
      type: "loot",
      w: 3,
      h: 2,
      rarity: "epic",
      rarityLabel: "史诗",
      rarityIcon: "🟣",
      category: "industrial",
      reclaimMin: 38000,
      minMarketPrice: 35000,
      maxMarketPrice: 80000,
      flavor:
        "高价值工业品。极其占格子——带一枚大钻头，还是带六块小电路板？",
      image: "img/market/heavy-industrial-drill.svg",
      model3d: "models/ornamental-orrery.glb",
    },
    helm_basic: {
      id: "helm_basic",
      name: "战术头盔",
      type: "helmet",
      w: 1,
      h: 1,
      image: "img/market/helmet.svg",
      model3d: "models/vintage-optical-sight.glb",
    },
    armr_basic: {
      id: "armr_basic",
      name: "轻型护甲",
      type: "armor",
      w: 1,
      h: 1,
      image: "img/market/armor.svg",
      model3d: "models/historical-lockbox.glb",
    },
    rig_light: {
      id: "rig_light",
      name: "轻型弹挂",
      type: "rig",
      w: 1,
      h: 1,
      rigSlots: 6,
      image: "img/market/rig-light.svg",
      model3d: "models/antique-lockbox.glb",
    },
    bp_sport: {
      id: "bp_sport",
      name: "蝰蛇轻型包",
      type: "backpack",
      w: 1,
      h: 1,
      cols: 2,
      rows: 4,
      minMarketPrice: 4500,
      maxMarketPrice: 6000,
      image: "img/market/backpack-sport.svg",
      model3d: "models/historical-lockbox.glb",
      flavor:
        "VIPER LIGHT PACK — 极其贴身，几乎不影响体力和奔跑速度。摸井盖、放弹匣和止痛药的入门首选。储物 2×4。",
    },
    bp_light: {
      id: "bp_light",
      name: "铁骑巡逻包",
      type: "backpack",
      w: 1,
      h: 1,
      cols: 3,
      rows: 4,
      minMarketPrice: 18000,
      maxMarketPrice: 22000,
      image: "img/market/backpack-light.svg",
      model3d: "models/historical-lockbox.glb",
      flavor:
        "IRON CAVALRY PATROL PACK — 标准军规面料，横向拓展到 3 格。略微增加体力消耗，但足够塞下大部分高价值武器和中型护甲。储物 3×4。",
    },
    bp_small: {
      id: "bp_small",
      name: "克里姆林包",
      type: "backpack",
      w: 1,
      h: 1,
      cols: 4,
      rows: 4,
      minMarketPrice: 65000,
      maxMarketPrice: 78000,
      image: "img/market/backpack-light.svg",
      model3d: "models/historical-lockbox.glb",
      flavor:
        "KREMLIN SQUARE PACK — 终极纯正方形空间。极其沉重（背上后无法使用快速撤离点），但只有它能装下等候厅最顶级的整枪和笨重的六角密匣。储物 4×4。",
    },
    bp_test: {
      id: "bp_test",
      name: "测试",
      type: "backpack",
      w: 1,
      h: 1,
      cols: 8,
      rows: 8,
      minMarketPrice: 0,
      maxMarketPrice: 0,
      image: "img/market/backpack-light.svg",
      model3d: "models/historical-lockbox.glb",
      flavor: "TEST PACK — 8×8 调试背包，仅供测试。",
    },
    brass_bullet: {
      id: "brass_bullet",
      name: "黄铜子弹",
      type: "ammo",
      w: 1,
      h: 1,
      stackSize: 60,
      rarity: "common",
      rarityLabel: "普通",
      rarityIcon: "🟢",
      category: "ammo",
      reclaimMin: 12000,
      flavor: "黄铜制式步枪弹，60 发装一组，占 1 格。",
      image: "img/market/brass-bullet.svg",
      model3d: "models/brass-bullet.glb",
    },
    uzi_smg: {
      id: "uzi_smg",
      name: "UZI冲锋枪",
      type: "weapon_primary",
      w: 3,
      h: 2,
      rarity: "rare",
      rarityLabel: "稀有",
      rarityIcon: "🔵",
      category: "weapon",
      reclaimMin: 2900,
      flavor: "改良冲锋枪，占 6 格，可装备主武器栏。",
      image: "img/market/uzi-smg.svg",
      model3d: "models/uzi.glb",
    },
    pirate_1001: {
      id: "pirate_1001",
      name: "军用电路板",
      type: "loot",
      w: 1,
      h: 1,
      rarity: "common",
      rarityLabel: "普通",
      rarityIcon: "🟢",
      reclaimMin: 500,
      minMarketPrice: 1000,
      maxMarketPrice: 1000,
      category: "collectible",
      model3d: "models/futuristic-device.glb",
    },
    pirate_1002: {
      id: "pirate_1002",
      name: "无人机镜头",
      type: "loot",
      w: 2,
      h: 2,
      rarity: "epic",
      rarityLabel: "史诗",
      rarityIcon: "🟣",
      reclaimMin: 60000,
      minMarketPrice: 100000,
      maxMarketPrice: 100000,
      category: "collectible",
      model3d: "models/vintage-optical-sight.glb",
    },
    pirate_1003: {
      id: "pirate_1003",
      name: "绝密航线硬盘",
      type: "loot",
      w: 1,
      h: 2,
      rarity: "epic",
      rarityLabel: "史诗",
      rarityIcon: "🟣",
      reclaimMin: 34000,
      minMarketPrice: 87000,
      maxMarketPrice: 87000,
      category: "collectible",
      model3d: "models/historical-lockbox.glb",
    },
    collectible_3001: {
      id: "collectible_3001",
      name: "合金打火机",
      type: "loot",
      w: 1,
      h: 1,
      rarity: "legendary",
      rarityLabel: "传奇",
      rarityIcon: "🟡",
      reclaimMin: 210000,
      minMarketPrice: 350000,
      maxMarketPrice: 350000,
      category: "collectible",
      flavor:
        "FRONT-LINE COMMANDER'S ALLOY LIGHTER — 战痕合金打火机，鹰徽与「FOR THE BRAVE」刻字。宝箱约 3.5% 产出。",
      image: "img/market/commander-alloy-lighter.png?v=2",
      model3d: "models/metallic-lighter.glb",
    },
    collectible_3002: {
      id: "collectible_3002",
      name: "废土八音盒",
      type: "loot",
      w: 1,
      h: 1,
      rarity: "legendary",
      rarityLabel: "传奇",
      rarityIcon: "🟡",
      reclaimMin: 160000,
      minMarketPrice: 260000,
      maxMarketPrice: 260000,
      category: "collectible",
      flavor:
        "OLD WORLD MELODIES — 废土手摇八音盒，黄铜机芯与星图顶盖，侧面刻有旧世旋律卷轴。宝箱约 4% 产出。",
      image: "img/market/wasteland-music-box.png",
      model3d: "models/steampunk-music-box.glb",
    },
    collectible_3003: {
      id: "collectible_3003",
      name: "全息推演沙盘",
      type: "loot",
      w: 2,
      h: 2,
      rarity: "epic",
      rarityLabel: "史诗",
      rarityIcon: "🟣",
      reclaimMin: 60000,
      minMarketPrice: 95000,
      maxMarketPrice: 95000,
      category: "collectible",
      flavor:
        "HOLOGRAPHIC TACTICAL SANDBOX — 金框战术推演台，投射紫青全息地形与单位标绘，用于战前沙盘推演。",
      image: "img/market/holographic-sand-table.png?v=1",
      model3d: "models/interactive-map-table.glb",
    },
    collectible_3004: {
      id: "collectible_3004",
      name: "微光观测镜",
      type: "loot",
      w: 1,
      h: 2,
      rarity: "epic",
      rarityLabel: "史诗",
      rarityIcon: "🟣",
      reclaimMin: 48000,
      minMarketPrice: 75000,
      maxMarketPrice: 75000,
      category: "collectible",
      flavor:
        "MODEL-1 NIGHTSIGHT — 黄铜镜筒与铭牌上的 61-85M 序列号，初代微光夜视观测镜，宝箱史诗档产出。",
      image: "img/market/micro-light-scope.png?v=1",
      model3d: "models/vintage-optical-sight.glb",
    },
    collectible_3005: {
      id: "collectible_3005",
      name: "极危荣誉章",
      type: "loot",
      w: 1,
      h: 1,
      rarity: "rare",
      rarityLabel: "稀有",
      rarityIcon: "🔵",
      reclaimMin: 24000,
      minMarketPrice: 38000,
      maxMarketPrice: 38000,
      category: "collectible",
      flavor:
        "DANGEROUS — 极危行动初代荣誉勋章，铜质罗盘星章与狮鹫盾徽，宝箱稀有档常见产出。",
      image: "img/market/honor-medal-gen1.png?v=1",
      model3d: "models/dangerous-badge.glb",
    },
    collectible_3006: {
      id: "collectible_3006",
      name: "红莲指挥仪",
      type: "loot",
      w: 3,
      h: 3,
      rarity: "mythic",
      rarityLabel: "神话",
      rarityIcon: "🔴",
      reclaimMin: 1300000,
      minMarketPrice: 1500000,
      maxMarketPrice: 1500000,
      category: "collectible",
      flavor:
        "CRIMSON LOTUS JUDGEMENT TIME CRYSTAL DIRECTOR — 殿堂级动态艺术藏品，红莲时间晶体与星轨矩阵，终极战略密钥。宝箱 0.5% 产出。",
      image: "img/market/crimson-lotus-director.png?v=1",
      model3d: "models/crimson-lotus-director.glb",
    },
    collectible_3007: {
      id: "collectible_3007",
      name: "永夜星象仪",
      type: "loot",
      w: 4,
      h: 4,
      rarity: "ultimate",
      rarityLabel: "终极",
      rarityIcon: "⬛",
      reclaimMin: 6300000,
      minMarketPrice: 7000000,
      maxMarketPrice: 7000000,
      category: "collectible",
      flavor:
        "EVERNIGHT AURORA OBSIDIAN STAR CHART — 黑曜石镜面与黑金浑天仪，底座微雕冷光封存永夜极光，纪念极危行动全面胜利的限量首席战略家藏品。宝箱 0.05% 产出。",
      image: "img/market/evernight-aurora-star-chart.png?v=1",
      model3d: "models/evernight-aurora-star-chart.glb",
    },
    collectible_3008: {
      id: "collectible_3008",
      name: "微缩新星",
      type: "loot",
      w: 1,
      h: 1,
      rarity: "ultimate",
      rarityLabel: "终极",
      rarityIcon: "⬛",
      reclaimMin: 11000000,
      minMarketPrice: 12000000,
      maxMarketPrice: 12000000,
      category: "collectible",
      flavor:
        "MINIATURE NOVA SINGULARITY BLACK-GOLD MONOCrystal — 坍缩黑金多面体，纳米金丝微雕，仅 1 格孤品。维持战术世界的能源奇点，提炼技术已失传，宝箱不产出。",
      image: "img/market/mini-nova-singularity-crystal.png?v=1",
      model3d: "models/mini-nova-singularity-crystal.glb",
    },
    pirate_1004: {
      id: "pirate_1004",
      name: "战术指挥鹰",
      type: "loot",
      w: 2,
      h: 2,
      rarity: "legendary",
      rarityLabel: "传奇",
      rarityIcon: "🟡",
      reclaimMin: 300000,
      minMarketPrice: 500000,
      maxMarketPrice: 500000,
      category: "collectible",
      flavor:
        "AQUILA TACTICA — 纯金铸造的战术指挥鹰，胸挂弹匣、头戴夜视，立于地球仪之上。海盗宝箱极低概率产出，黑市标价五十万。",
      image: "img/market/aquila-tactica-eagle.png?v=2",
      model3d: "models/tactical-command-eagle-statue.glb",
    },
    pirate_1005: {
      id: "pirate_1005",
      name: "未知血清",
      type: "loot",
      w: 1,
      h: 1,
      rarity: "legendary",
      rarityLabel: "传奇",
      rarityIcon: "🟡",
      reclaimMin: 250000,
      minMarketPrice: 450000,
      maxMarketPrice: 450000,
      category: "collectible",
      model3d: "models/mini-nova-singularity-crystal.glb",
    },
    pirate_1006: {
      id: "pirate_1006",
      name: "军用对讲机",
      type: "loot",
      w: 1,
      h: 1,
      rarity: "rare",
      rarityLabel: "稀有",
      rarityIcon: "🔵",
      reclaimMin: 3000,
      minMarketPrice: 10000,
      maxMarketPrice: 10000,
      category: "collectible",
      model3d: "models/futuristic-device.glb",
    },
    pirate_1007: {
      id: "pirate_1007",
      name: "损坏夜视仪",
      type: "loot",
      w: 1,
      h: 2,
      reclaimMin: 9000,
      category: "collectible",
      model3d: "models/vintage-optical-sight.glb",
    },
  };

  var STASH_TO_ITEM = {
    circuit: "circuit",
    spoil: "sealed_motor_oil",
    hidrl: "heavy_industrial_drill",
    helm1: "helm_basic",
    armr1: "armr_basic",
    riglt: "rig_light",
    bpspt: "bp_sport",
    bplgt: "bp_light",
    bpsm4: "bp_small",
    bptst: "bp_test",
    brslv: "brass_bullet",
    uzism: "uzi_smg",
    p1001: "pirate_1001",
    p1002: "pirate_1002",
    p1003: "pirate_1003",
    p1004: "pirate_1004",
    p1005: "pirate_1005",
    p1006: "pirate_1006",
    c3001: "collectible_3001",
    c3002: "collectible_3002",
    c3003: "collectible_3003",
    c3004: "collectible_3004",
    c3005: "collectible_3005",
    c3006: "collectible_3006",
    c3007: "collectible_3007",
    c3008: "collectible_3008",
    kpoff: "keycard_president_office",
  };

  var SLOT_TYPES = {
    primary: ["weapon_primary"],
    melee: ["weapon_melee"],
    secondary: ["weapon_secondary"],
    pistol: ["weapon_pistol"],
    helmet: ["helmet"],
    armor: ["armor"],
    rig: ["rig"],
    backpack: ["backpack"],
    card: ["keycard", "loot"],
  };

  function getItem(id) {
    return ITEMS[id] ? Object.assign({}, ITEMS[id]) : null;
  }

  function fromStashId(stashId) {
    var itemId = STASH_TO_ITEM[stashId];
    return itemId ? getItem(itemId) : null;
  }

  function acceptsSlot(slotKey, item) {
    if (!item) return false;
    var allowed = SLOT_TYPES[slotKey];
    if (!allowed) return false;
    if (allowed.indexOf(item.type) >= 0) return true;
    if (slotKey === "card" && item.type === "loot") return true;
    return false;
  }

  function getModel3d(id) {
    var item = ITEMS[id];
    return item && item.model3d ? item.model3d : null;
  }

  function canDropAsWorldModel(id) {
    return !!getModel3d(id);
  }

  function getAllModel3dUrls() {
    var urls = [];
    var seen = Object.create(null);
    var key;
    for (key in ITEMS) {
      if (!Object.prototype.hasOwnProperty.call(ITEMS, key)) continue;
      var url = ITEMS[key].model3d;
      if (!url || seen[url]) continue;
      seen[url] = true;
      urls.push(url);
    }
    return urls;
  }

  window.ItemCatalog = {
    ITEMS: ITEMS,
    STASH_TO_ITEM: STASH_TO_ITEM,
    getItem: getItem,
    fromStashId: fromStashId,
    acceptsSlot: acceptsSlot,
    getModel3d: getModel3d,
    canDropAsWorldModel: canDropAsWorldModel,
    getAllModel3dUrls: getAllModel3dUrls,
  };
})();
